In [4]:
!pip install numpy

In [7]:
import numpy as np

In [8]:
array_of_zeroes = np.zeros((3,4))

array_of_zeroes

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [9]:
array_of_zeros_int = np.zeros((4,5),dtype=np.int16)

array_of_zeros_int

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]], dtype=int16)

In [11]:
array_2d = np.array([(2,3,4),(5,6,7)])

array_2d

array([[2, 3, 4],
       [5, 6, 7]])

In [12]:
array_2d.shape

(2, 3)

In [13]:
np.arange(6)

array([0, 1, 2, 3, 4, 5])

In [15]:
array_nd = np.arange(6).reshape(3,2)

array_nd

array([[0, 1],
       [2, 3],
       [4, 5]])

In [16]:
array_nd.shape

(3, 2)

In [17]:
a=np.array([6,6,6])

b=np.array([3,3,3])

a+b

array([9, 9, 9])

In [18]:
a-b

array([3, 3, 3])

In [19]:
a*b

array([18, 18, 18])

In [20]:
a/b

array([2., 2., 2.])

In [23]:
a<10

array([ True,  True,  True])

In [24]:
a>10

array([False, False, False])

In [25]:
a**2

array([36, 36, 36], dtype=int32)

In [26]:
b**2

array([9, 9, 9], dtype=int32)

In [28]:
A = np.array([(1,2),(3,4)])
B = np.array((1,2),(3,4))

print('A:\n',A)
print('B:\n',B)

TypeError: data type not understood

In [29]:
A = np.array([(1,2),(3,4)])
B = np.array([(1,2),(3,4)])

print('A:\n',A)
print('B:\n',B)

A:
 [[1 2]
 [3 4]]
B:
 [[1 2]
 [3 4]]


In [30]:
A*B

array([[ 1,  4],
       [ 9, 16]])