In [6]:
!pip install numpy

In [7]:
import numpy as np

In [8]:
ipl_teams=["csk","mi","srh","kkr","rcb"]

ipl = np.array(ipl_teams)

In [9]:
ipl

array(['csk', 'mi', 'srh', 'kkr', 'rcb'], dtype='<U3')

In [10]:
type(ipl)

numpy.ndarray

In [11]:
ipl_teams2 = ["kxip","dc","rr"]

ipl2 = np.array(ipl_teams2)

ipl2

array(['kxip', 'dc', 'rr'], dtype='<U4')

In [33]:
array1 = [1,2,3,4]

arrayop = np.array(array1)

In [34]:
array1

[1, 2, 3, 4]

In [36]:
type(arrayop)

numpy.ndarray

In [37]:
type(array1)

list

In [13]:
array_of_zeros = np.zeros((3,4))

array_of_zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [14]:
array_of_ones = np.ones((4,5))

array_of_ones

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [16]:
array_eye = np.eye(4)

array_eye

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [17]:
array_of_even = np.arange(2,50,2)

array_of_even

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38, 40, 42, 44, 46, 48])

In [26]:
array_2d = np.array([(2,3,4,4),(1,2,3,5)])

array_2d

array([[2, 3, 4, 4],
       [1, 2, 3, 5]])

In [27]:
array_2d.shape

(2, 4)

In [28]:
array_2d1 = np.array([(2,3,4),(1,2,3,5)])

array_2d1

array([(2, 3, 4), (1, 2, 3, 5)], dtype=object)

In [31]:
array_2d1.shape

(2,)

In [30]:
array_2d2 = np.array([(2,3,4,5),(1,2,3)])

array_2d2

array([(2, 3, 4, 5), (1, 2, 3)], dtype=object)

In [32]:
array_2d2.shape

(2,)